<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.2.0</Version>
    <Authors>HKW</Authors>
    <Company>HKW</Company>
    <PackageDescription>A common value or multi value converter base.</PackageDescription>
    <PackageTags>Converter</PackageTags>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <PathMap Condition="'$(SolutionDir)' != ''">$(SolutionDir)=/_/</PathMap>
    <PathMap Condition="'$(SolutionDir)' == ''"
      >$(MSBuildProjectDirectory)=/_/$(AssemblyName)/</PathMap
    >
  </PropertyGroup>

  <!--<ItemGroup>
    <Reference Include="HKW.Utils">
      <HintPath>..\..\HKW.Utils\HKW.Utils\bin\Debug\net10.0\HKW.Utils.dll</HintPath>
    </Reference>
  </ItemGroup>-->
  <ItemGroup>
    <PackageReference Include="HKW.Utils" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
</Project>
